# SPDX-FileCopyrightText: 2024 SAP SE and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

apiVersion: v1
kind: Service
metadata:
  name: {{ template "prisma.fullname" . }}
  labels:
    app: {{ template "prisma.name" . }}
    chart: {{ template "prisma.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: service
      port: {{ .Values.service.port }}
      protocol: TCP
      targetPort: prisma
  selector:
    app: {{ template "prisma.name" . }}
    release: {{ .Release.Name }}
