# SPDX-FileCopyrightText: 2024 SAP SE and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "prisma.name" . }}
    chart: {{ template "prisma.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "prisma.serviceAccountName" . }}
{{- end }}
