header:
  license:
    spdx-id: Apache-2.0
    copyright-owner: Apache Software Foundation

  paths: # `paths` are the path list that will be checked (and fixed) by license-eye, default is ['**'].
    - '**'

  paths-ignore:
    - 'dist'
    - 'licenses'
    - '**/*.md'
    - 'LICENSE'
    - 'NOTICE'
    - '**/go.mod'
    - '**/go.sum'
    - '**/**/.helmignore'
    - '**/**/requirements.lock'
    - '**/**/templates/NOTES.txt'
    - '.github/workflows/**'
    - '.github/**.yaml'
    

  comment: on-failure
  
  # license-location-threshold specifies the index threshold where the license header can be located,
  # after all, a "header" cannot be TOO far from the file start.
  license-location-threshold: 80

  language:
    Go:
      extensions:
        - ".go"
      comment_style_id: DoubleSlash
