# SPDX-FileCopyrightText: 2024 SAP SE and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- range $path, $bytes := .Files.Glob "crds/*.yaml" }}
{{ $.Files.Get $path }}
---
{{- end }}

