# SPDX-FileCopyrightText: 2024 SAP SE and Greenhouse contributors
# SPDX-License-Identifier: Apache-2.0

{{- if and .Values.alertmanager.enabled .Values.rbac.create .Values.alertmanager.useClusterRole -}}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "prometheus.alertmanager.labels" . | nindent 4 }}
  name: {{ template "prometheus.alertmanager.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "prometheus.serviceAccountName.alertmanager" . }}
{{ include "prometheus.namespace" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
{{- if (not .Values.alertmanager.useExistingRole) }}
  name: {{ template "prometheus.alertmanager.fullname" . }}
{{- else }}
  name: {{ .Values.alertmanager.useExistingRole }}
{{- end }}
{{- end }}
