name: Check License Header
on:
  workflow_dispatch: {}
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build-license-eye:
    name: Build LicenseEye
    runs-on: [ oci-runner ]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: 1.21

      - name: Check License Header
        uses: apache/skywalking-eyes/header@v0.5.0
        with:
            config: .github/licenserc.yaml
            mode: check
